### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by felipechalreo** [quarnster/ff6#1]
It doesn't work with the latest update.

**Comment by quarnster** [comment]
Worked fine for me still on Android. Did you make sure to edit the .json which has the highest `FileHeader -> Version` number? The one with the highest number is the one that'll be loaded and the other ignored so either make the changes to the one with the highest number or both of the json files.

If you did, please provide more information on exactly what's not working.

**Comment by felipechalreo** [comment]
Oh that was my mistake and for some reason when I moved the files back to the phone, it changed the proprieties not allowing the game to writing it, so I changed back to 777 and it worked :+1: 
I can't thank you enough for the good work :smile:
